/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_Supprimer_window (void)
{
  GtkWidget *Supprimer_window;
  GtkWidget *fixed4;
  GtkWidget *label_Texte;
  GtkWidget *button_Supprimer_oui;
  GtkWidget *button_Supprimer_Annuler;

  Supprimer_window = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (Supprimer_window), _("Supprimer "));

  fixed4 = gtk_fixed_new ();
  gtk_widget_show (fixed4);
  gtk_container_add (GTK_CONTAINER (Supprimer_window), fixed4);
  gtk_widget_set_size_request (fixed4, 400, 200);

  label_Texte = gtk_label_new (_("  Voulez-vous vraiment \nsupprimer cet personne"));
  gtk_widget_show (label_Texte);
  gtk_fixed_put (GTK_FIXED (fixed4), label_Texte, 40, 0);
  gtk_widget_set_size_request (label_Texte, 300, 150);

  button_Supprimer_oui = gtk_button_new_with_mnemonic (_("OUI"));
  gtk_widget_show (button_Supprimer_oui);
  gtk_fixed_put (GTK_FIXED (fixed4), button_Supprimer_oui, 240, 144);
  gtk_widget_set_size_request (button_Supprimer_oui, 80, 35);

  button_Supprimer_Annuler = gtk_button_new_with_mnemonic (_("Annuler"));
  gtk_widget_show (button_Supprimer_Annuler);
  gtk_fixed_put (GTK_FIXED (fixed4), button_Supprimer_Annuler, 64, 144);
  gtk_widget_set_size_request (button_Supprimer_Annuler, 80, 35);

  g_signal_connect ((gpointer) button_Supprimer_oui, "clicked",
                    G_CALLBACK (on_button_Supprimer_oui_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_Supprimer_Annuler, "clicked",
                    G_CALLBACK (on_button_Supprimer_Annuler_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (Supprimer_window, Supprimer_window, "Supprimer_window");
  GLADE_HOOKUP_OBJECT (Supprimer_window, fixed4, "fixed4");
  GLADE_HOOKUP_OBJECT (Supprimer_window, label_Texte, "label_Texte");
  GLADE_HOOKUP_OBJECT (Supprimer_window, button_Supprimer_oui, "button_Supprimer_oui");
  GLADE_HOOKUP_OBJECT (Supprimer_window, button_Supprimer_Annuler, "button_Supprimer_Annuler");

  return Supprimer_window;
}

GtkWidget*
create_administrateur_window (void)
{
  GtkWidget *administrateur_window;
  GtkWidget *notebook1;
  GtkWidget *fixed12;
  GtkWidget *entry_aj_nom_WT;
  GtkWidget *entry_aj_prenom_WT;
  GtkWidget *entry_aj_cin_WT;
  GtkWidget *entry_aj_telephone_WT;
  GtkObject *spinbutton_aj_jour_naissance_WT_adj;
  GtkWidget *spinbutton_aj_jour_naissance_WT;
  GtkObject *spinbutton_aj_mois_naissance_WT_adj;
  GtkWidget *spinbutton_aj_mois_naissance_WT;
  GtkObject *spinbutton_aj_annee_naissance_WT_adj;
  GtkWidget *spinbutton_aj_annee_naissance_WT;
  GtkObject *spinbutton_aj_mois_recrut_WT_adj;
  GtkWidget *spinbutton_aj_mois_recrut_WT;
  GtkObject *spinbutton_aj_annee_recrut_WT_adj;
  GtkWidget *spinbutton_aj_annee_recrut_WT;
  GtkWidget *entry_aj_id_WT;
  GtkWidget *entry_aj_mdp_WT;
  GtkObject *spinbutton_aj_jour_recrut_WT_adj;
  GtkWidget *spinbutton_aj_jour_recrut_WT;
  GtkWidget *label_nom;
  GtkWidget *label_role;
  GtkWidget *label_cin;
  GtkWidget *label_tele;
  GtkWidget *label_sexe;
  GtkWidget *label_date_naissance;
  GtkWidget *label_date_recrut;
  GtkWidget *label_id;
  GtkWidget *label_mdp;
  GtkWidget *label_jour_naissance;
  GtkWidget *label_mois_naissance;
  GtkWidget *label_annee_naissance;
  GtkWidget *label_jour_recrut;
  GtkWidget *label_mois_recrut;
  GtkWidget *label_annee_recrut;
  GtkWidget *label_pre;
  GtkWidget *comboboxentry_aj_role_WT;
  GtkWidget *button_aj_annuler_WT;
  GtkWidget *alignment3;
  GtkWidget *hbox2;
  GtkWidget *image2;
  GtkWidget *label87;
  GtkWidget *button_aj_ajouter_WT;
  GtkWidget *alignment2;
  GtkWidget *hbox1;
  GtkWidget *image1;
  GtkWidget *label86;
  GtkWidget *radiobutton_aj_homme_WT;
  GSList *radiobutton_aj_homme_WT_group = NULL;
  GtkWidget *radiobutton_aj_femme_WT;
  GtkWidget *label_ajouter;
  GtkWidget *fixed11;
  GtkWidget *entry_mod_nom_WT;
  GtkWidget *entry_mod_prenom_WT;
  GtkWidget *entry_mod_cin_WT;
  GtkWidget *entry_mod_tele_WT;
  GtkObject *spinbutton_mod_jour_recrut_WT_adj;
  GtkWidget *spinbutton_mod_jour_recrut_WT;
  GtkObject *spinbutton_mod_jour_naissance_WT_adj;
  GtkWidget *spinbutton_mod_jour_naissance_WT;
  GtkObject *spinbutton_mod_mois_naissance_WT_adj;
  GtkWidget *spinbutton_mod_mois_naissance_WT;
  GtkObject *spinbutton_mod_mois_recrut_WT_adj;
  GtkWidget *spinbutton_mod_mois_recrut_WT;
  GtkObject *spinbutton_mod_annee_naissance_WT_adj;
  GtkWidget *spinbutton_mod_annee_naissance_WT;
  GtkObject *spinbutton_mod_annee_recrut_WT_adj;
  GtkWidget *spinbutton_mod_annee_recrut_WT;
  GtkWidget *entry_mod_id_WT;
  GtkWidget *entry_mod_mdp_WT;
  GtkWidget *label_nom_mod;
  GtkWidget *label_pre_mod;
  GtkWidget *label_role_mod;
  GtkWidget *label_cin_role;
  GtkWidget *label_tele_mod;
  GtkWidget *label_sexe_mod;
  GtkWidget *label_mdp_mod;
  GtkWidget *label_id_mod;
  GtkWidget *label_date_naissance_mod;
  GtkWidget *label_jour_naissance_mod;
  GtkWidget *label_mois_naissance_mod;
  GtkWidget *label_annee_naissance_mod;
  GtkWidget *label_date_recrut_mod;
  GtkWidget *label_jour_recrut_mod;
  GtkWidget *label_mois_recrut_mod;
  GtkWidget *label_annee_recrut_mod;
  GtkWidget *comboboxentry_mod_role_WT;
  GtkWidget *button_mod_annuler_WT;
  GtkWidget *alignment5;
  GtkWidget *hbox4;
  GtkWidget *image4;
  GtkWidget *label89;
  GtkWidget *button_mod_modif_WT;
  GtkWidget *alignment7;
  GtkWidget *hbox6;
  GtkWidget *image6;
  GtkWidget *label95;
  GtkWidget *radiobutton_mod_homme_WT;
  GSList *radiobutton_mod_homme_WT_group = NULL;
  GtkWidget *radiobutton_mod_femme_WT;
  GtkWidget *label_modifier;
  GtkWidget *fixed10;
  GtkWidget *entry_rechercher_WT;
  GtkWidget *label1;
  GtkWidget *comboboxentry_liste_role_WT;
  GtkWidget *scrolledwindow1;
  GtkWidget *treeview_liste_WT;
  GtkWidget *label_poucentage_homme;
  GtkWidget *label_pourcentage_femme;
  GtkWidget *label_homme;
  GtkWidget *label_femme;
  GtkWidget *label_afficher;
  GtkWidget *fixed9;
  GtkWidget *entry_sup_id_WT;
  GtkWidget *button_Supprimer_WT;
  GtkWidget *alignment6;
  GtkWidget *hbox5;
  GtkWidget *image5;
  GtkWidget *label94;
  GtkWidget *label_supprimer;

  administrateur_window = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (administrateur_window, 1200, 800);
  gtk_window_set_title (GTK_WINDOW (administrateur_window), _("ESPACE ADMINISTRATEUR"));

  notebook1 = gtk_notebook_new ();
  gtk_widget_show (notebook1);
  gtk_container_add (GTK_CONTAINER (administrateur_window), notebook1);
  gtk_notebook_set_tab_pos (GTK_NOTEBOOK (notebook1), GTK_POS_LEFT);

  fixed12 = gtk_fixed_new ();
  gtk_widget_show (fixed12);
  gtk_container_add (GTK_CONTAINER (notebook1), fixed12);

  entry_aj_nom_WT = gtk_entry_new ();
  gtk_widget_show (entry_aj_nom_WT);
  gtk_fixed_put (GTK_FIXED (fixed12), entry_aj_nom_WT, 300, 30);
  gtk_widget_set_size_request (entry_aj_nom_WT, 300, 50);
  gtk_entry_set_text (GTK_ENTRY (entry_aj_nom_WT), _(" "));
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_aj_nom_WT), 8226);

  entry_aj_prenom_WT = gtk_entry_new ();
  gtk_widget_show (entry_aj_prenom_WT);
  gtk_fixed_put (GTK_FIXED (fixed12), entry_aj_prenom_WT, 300, 100);
  gtk_widget_set_size_request (entry_aj_prenom_WT, 300, 50);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_aj_prenom_WT), 8226);

  entry_aj_cin_WT = gtk_entry_new ();
  gtk_widget_show (entry_aj_cin_WT);
  gtk_fixed_put (GTK_FIXED (fixed12), entry_aj_cin_WT, 300, 240);
  gtk_widget_set_size_request (entry_aj_cin_WT, 300, 50);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_aj_cin_WT), 8226);

  entry_aj_telephone_WT = gtk_entry_new ();
  gtk_widget_show (entry_aj_telephone_WT);
  gtk_fixed_put (GTK_FIXED (fixed12), entry_aj_telephone_WT, 300, 310);
  gtk_widget_set_size_request (entry_aj_telephone_WT, 300, 50);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_aj_telephone_WT), 8226);

  spinbutton_aj_jour_naissance_WT_adj = gtk_adjustment_new (1, 1, 31, 1, 10, 10);
  spinbutton_aj_jour_naissance_WT = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton_aj_jour_naissance_WT_adj), 1, 0);
  gtk_widget_show (spinbutton_aj_jour_naissance_WT);
  gtk_fixed_put (GTK_FIXED (fixed12), spinbutton_aj_jour_naissance_WT, 300, 460);
  gtk_widget_set_size_request (spinbutton_aj_jour_naissance_WT, 60, 27);

  spinbutton_aj_mois_naissance_WT_adj = gtk_adjustment_new (1, 1, 12, 1, 10, 10);
  spinbutton_aj_mois_naissance_WT = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton_aj_mois_naissance_WT_adj), 1, 0);
  gtk_widget_show (spinbutton_aj_mois_naissance_WT);
  gtk_fixed_put (GTK_FIXED (fixed12), spinbutton_aj_mois_naissance_WT, 420, 460);
  gtk_widget_set_size_request (spinbutton_aj_mois_naissance_WT, 60, 27);

  spinbutton_aj_annee_naissance_WT_adj = gtk_adjustment_new (1950, 1950, 2023, 1, 10, 10);
  spinbutton_aj_annee_naissance_WT = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton_aj_annee_naissance_WT_adj), 1, 0);
  gtk_widget_show (spinbutton_aj_annee_naissance_WT);
  gtk_fixed_put (GTK_FIXED (fixed12), spinbutton_aj_annee_naissance_WT, 540, 460);
  gtk_widget_set_size_request (spinbutton_aj_annee_naissance_WT, 60, 27);

  spinbutton_aj_mois_recrut_WT_adj = gtk_adjustment_new (1, 1, 12, 1, 10, 10);
  spinbutton_aj_mois_recrut_WT = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton_aj_mois_recrut_WT_adj), 1, 0);
  gtk_widget_show (spinbutton_aj_mois_recrut_WT);
  gtk_fixed_put (GTK_FIXED (fixed12), spinbutton_aj_mois_recrut_WT, 420, 530);
  gtk_widget_set_size_request (spinbutton_aj_mois_recrut_WT, 60, 27);

  spinbutton_aj_annee_recrut_WT_adj = gtk_adjustment_new (1990, 1990, 2023, 1, 10, 10);
  spinbutton_aj_annee_recrut_WT = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton_aj_annee_recrut_WT_adj), 1, 0);
  gtk_widget_show (spinbutton_aj_annee_recrut_WT);
  gtk_fixed_put (GTK_FIXED (fixed12), spinbutton_aj_annee_recrut_WT, 540, 530);
  gtk_widget_set_size_request (spinbutton_aj_annee_recrut_WT, 60, 27);

  entry_aj_id_WT = gtk_entry_new ();
  gtk_widget_show (entry_aj_id_WT);
  gtk_fixed_put (GTK_FIXED (fixed12), entry_aj_id_WT, 300, 590);
  gtk_widget_set_size_request (entry_aj_id_WT, 300, 50);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_aj_id_WT), 8226);

  entry_aj_mdp_WT = gtk_entry_new ();
  gtk_widget_show (entry_aj_mdp_WT);
  gtk_fixed_put (GTK_FIXED (fixed12), entry_aj_mdp_WT, 300, 660);
  gtk_widget_set_size_request (entry_aj_mdp_WT, 300, 50);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_aj_mdp_WT), 8226);

  spinbutton_aj_jour_recrut_WT_adj = gtk_adjustment_new (1, 1, 31, 1, 10, 10);
  spinbutton_aj_jour_recrut_WT = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton_aj_jour_recrut_WT_adj), 1, 0);
  gtk_widget_show (spinbutton_aj_jour_recrut_WT);
  gtk_fixed_put (GTK_FIXED (fixed12), spinbutton_aj_jour_recrut_WT, 300, 530);
  gtk_widget_set_size_request (spinbutton_aj_jour_recrut_WT, 60, 27);

  label_nom = gtk_label_new (_("Nom :"));
  gtk_widget_show (label_nom);
  gtk_fixed_put (GTK_FIXED (fixed12), label_nom, 50, 30);
  gtk_widget_set_size_request (label_nom, 200, 50);

  label_role = gtk_label_new (_("Role :"));
  gtk_widget_show (label_role);
  gtk_fixed_put (GTK_FIXED (fixed12), label_role, 50, 170);
  gtk_widget_set_size_request (label_role, 200, 50);

  label_cin = gtk_label_new (_("CIN :"));
  gtk_widget_show (label_cin);
  gtk_fixed_put (GTK_FIXED (fixed12), label_cin, 50, 240);
  gtk_widget_set_size_request (label_cin, 200, 50);

  label_tele = gtk_label_new (_("T\303\251l\303\251phone  :"));
  gtk_widget_show (label_tele);
  gtk_fixed_put (GTK_FIXED (fixed12), label_tele, 50, 310);
  gtk_widget_set_size_request (label_tele, 200, 50);

  label_sexe = gtk_label_new (_("Sexe :"));
  gtk_widget_show (label_sexe);
  gtk_fixed_put (GTK_FIXED (fixed12), label_sexe, 50, 380);
  gtk_widget_set_size_request (label_sexe, 200, 50);

  label_date_naissance = gtk_label_new (_("Date de naissance :"));
  gtk_widget_show (label_date_naissance);
  gtk_fixed_put (GTK_FIXED (fixed12), label_date_naissance, 50, 450);
  gtk_widget_set_size_request (label_date_naissance, 200, 50);

  label_date_recrut = gtk_label_new (_("Date de recrutement :"));
  gtk_widget_show (label_date_recrut);
  gtk_fixed_put (GTK_FIXED (fixed12), label_date_recrut, 50, 520);
  gtk_widget_set_size_request (label_date_recrut, 200, 50);

  label_id = gtk_label_new (_("Idantifiant :"));
  gtk_widget_show (label_id);
  gtk_fixed_put (GTK_FIXED (fixed12), label_id, 50, 590);
  gtk_widget_set_size_request (label_id, 200, 50);

  label_mdp = gtk_label_new (_("Mot de passe :"));
  gtk_widget_show (label_mdp);
  gtk_fixed_put (GTK_FIXED (fixed12), label_mdp, 50, 660);
  gtk_widget_set_size_request (label_mdp, 200, 50);

  label_jour_naissance = gtk_label_new (_("jour"));
  gtk_widget_show (label_jour_naissance);
  gtk_fixed_put (GTK_FIXED (fixed12), label_jour_naissance, 240, 450);
  gtk_widget_set_size_request (label_jour_naissance, 70, 50);

  label_mois_naissance = gtk_label_new (_("mois"));
  gtk_widget_show (label_mois_naissance);
  gtk_fixed_put (GTK_FIXED (fixed12), label_mois_naissance, 360, 450);
  gtk_widget_set_size_request (label_mois_naissance, 70, 50);

  label_annee_naissance = gtk_label_new (_("ann\303\251\303\251"));
  gtk_widget_show (label_annee_naissance);
  gtk_fixed_put (GTK_FIXED (fixed12), label_annee_naissance, 480, 450);
  gtk_widget_set_size_request (label_annee_naissance, 70, 50);

  label_jour_recrut = gtk_label_new (_("jour"));
  gtk_widget_show (label_jour_recrut);
  gtk_fixed_put (GTK_FIXED (fixed12), label_jour_recrut, 240, 520);
  gtk_widget_set_size_request (label_jour_recrut, 70, 50);

  label_mois_recrut = gtk_label_new (_("mois"));
  gtk_widget_show (label_mois_recrut);
  gtk_fixed_put (GTK_FIXED (fixed12), label_mois_recrut, 360, 520);
  gtk_widget_set_size_request (label_mois_recrut, 70, 50);

  label_annee_recrut = gtk_label_new (_("ann\303\251e"));
  gtk_widget_show (label_annee_recrut);
  gtk_fixed_put (GTK_FIXED (fixed12), label_annee_recrut, 480, 520);
  gtk_widget_set_size_request (label_annee_recrut, 70, 50);

  label_pre = gtk_label_new (_("Pr\303\251nom :"));
  gtk_widget_show (label_pre);
  gtk_fixed_put (GTK_FIXED (fixed12), label_pre, 50, 100);
  gtk_widget_set_size_request (label_pre, 200, 50);

  comboboxentry_aj_role_WT = gtk_combo_box_entry_new_text ();
  gtk_widget_show (comboboxentry_aj_role_WT);
  gtk_fixed_put (GTK_FIXED (fixed12), comboboxentry_aj_role_WT, 300, 170);
  gtk_widget_set_size_request (comboboxentry_aj_role_WT, 300, 50);
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry_aj_role_WT), _("Medecin"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry_aj_role_WT), _("Infermier"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry_aj_role_WT), _("Responsable"));

  button_aj_annuler_WT = gtk_button_new ();
  gtk_widget_show (button_aj_annuler_WT);
  gtk_fixed_put (GTK_FIXED (fixed12), button_aj_annuler_WT, 650, 400);
  gtk_widget_set_size_request (button_aj_annuler_WT, 200, 70);

  alignment3 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment3);
  gtk_container_add (GTK_CONTAINER (button_aj_annuler_WT), alignment3);

  hbox2 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox2);
  gtk_container_add (GTK_CONTAINER (alignment3), hbox2);

  image2 = gtk_image_new_from_stock ("gtk-cancel", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image2);
  gtk_box_pack_start (GTK_BOX (hbox2), image2, FALSE, FALSE, 0);

  label87 = gtk_label_new_with_mnemonic (_("   ANNULER"));
  gtk_widget_show (label87);
  gtk_box_pack_start (GTK_BOX (hbox2), label87, FALSE, FALSE, 0);

  button_aj_ajouter_WT = gtk_button_new ();
  gtk_widget_show (button_aj_ajouter_WT);
  gtk_fixed_put (GTK_FIXED (fixed12), button_aj_ajouter_WT, 650, 300);
  gtk_widget_set_size_request (button_aj_ajouter_WT, 200, 70);

  alignment2 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment2);
  gtk_container_add (GTK_CONTAINER (button_aj_ajouter_WT), alignment2);

  hbox1 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox1);
  gtk_container_add (GTK_CONTAINER (alignment2), hbox1);

  image1 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image1);
  gtk_box_pack_start (GTK_BOX (hbox1), image1, FALSE, FALSE, 0);

  label86 = gtk_label_new_with_mnemonic (_("   AJOUTER"));
  gtk_widget_show (label86);
  gtk_box_pack_start (GTK_BOX (hbox1), label86, FALSE, FALSE, 0);

  radiobutton_aj_homme_WT = gtk_radio_button_new_with_mnemonic (NULL, _("HOMME"));
  gtk_widget_show (radiobutton_aj_homme_WT);
  gtk_fixed_put (GTK_FIXED (fixed12), radiobutton_aj_homme_WT, 300, 380);
  gtk_widget_set_size_request (radiobutton_aj_homme_WT, 150, 50);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton_aj_homme_WT), radiobutton_aj_homme_WT_group);
  radiobutton_aj_homme_WT_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton_aj_homme_WT));

  radiobutton_aj_femme_WT = gtk_radio_button_new_with_mnemonic (NULL, _("FEMME"));
  gtk_widget_show (radiobutton_aj_femme_WT);
  gtk_fixed_put (GTK_FIXED (fixed12), radiobutton_aj_femme_WT, 450, 380);
  gtk_widget_set_size_request (radiobutton_aj_femme_WT, 150, 50);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton_aj_femme_WT), radiobutton_aj_homme_WT_group);
  radiobutton_aj_homme_WT_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton_aj_femme_WT));

  label_ajouter = gtk_label_new (_("AJOUTER"));
  gtk_widget_show (label_ajouter);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 0), label_ajouter);
  gtk_widget_set_size_request (label_ajouter, 250, 80);

  fixed11 = gtk_fixed_new ();
  gtk_widget_show (fixed11);
  gtk_container_add (GTK_CONTAINER (notebook1), fixed11);

  entry_mod_nom_WT = gtk_entry_new ();
  gtk_widget_show (entry_mod_nom_WT);
  gtk_fixed_put (GTK_FIXED (fixed11), entry_mod_nom_WT, 300, 30);
  gtk_widget_set_size_request (entry_mod_nom_WT, 300, 50);
  gtk_entry_set_text (GTK_ENTRY (entry_mod_nom_WT), _(" "));
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_mod_nom_WT), 8226);

  entry_mod_prenom_WT = gtk_entry_new ();
  gtk_widget_show (entry_mod_prenom_WT);
  gtk_fixed_put (GTK_FIXED (fixed11), entry_mod_prenom_WT, 300, 100);
  gtk_widget_set_size_request (entry_mod_prenom_WT, 300, 50);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_mod_prenom_WT), 8226);

  entry_mod_cin_WT = gtk_entry_new ();
  gtk_widget_show (entry_mod_cin_WT);
  gtk_fixed_put (GTK_FIXED (fixed11), entry_mod_cin_WT, 300, 240);
  gtk_widget_set_size_request (entry_mod_cin_WT, 300, 50);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_mod_cin_WT), 8226);

  entry_mod_tele_WT = gtk_entry_new ();
  gtk_widget_show (entry_mod_tele_WT);
  gtk_fixed_put (GTK_FIXED (fixed11), entry_mod_tele_WT, 300, 310);
  gtk_widget_set_size_request (entry_mod_tele_WT, 300, 50);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_mod_tele_WT), 8226);

  spinbutton_mod_jour_recrut_WT_adj = gtk_adjustment_new (1, 1, 31, 1, 10, 10);
  spinbutton_mod_jour_recrut_WT = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton_mod_jour_recrut_WT_adj), 1, 0);
  gtk_widget_show (spinbutton_mod_jour_recrut_WT);
  gtk_fixed_put (GTK_FIXED (fixed11), spinbutton_mod_jour_recrut_WT, 300, 530);
  gtk_widget_set_size_request (spinbutton_mod_jour_recrut_WT, 60, 27);

  spinbutton_mod_jour_naissance_WT_adj = gtk_adjustment_new (1, 1, 31, 1, 10, 10);
  spinbutton_mod_jour_naissance_WT = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton_mod_jour_naissance_WT_adj), 1, 0);
  gtk_widget_show (spinbutton_mod_jour_naissance_WT);
  gtk_fixed_put (GTK_FIXED (fixed11), spinbutton_mod_jour_naissance_WT, 300, 460);
  gtk_widget_set_size_request (spinbutton_mod_jour_naissance_WT, 60, 27);

  spinbutton_mod_mois_naissance_WT_adj = gtk_adjustment_new (1, 1, 12, 1, 10, 10);
  spinbutton_mod_mois_naissance_WT = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton_mod_mois_naissance_WT_adj), 1, 0);
  gtk_widget_show (spinbutton_mod_mois_naissance_WT);
  gtk_fixed_put (GTK_FIXED (fixed11), spinbutton_mod_mois_naissance_WT, 420, 460);
  gtk_widget_set_size_request (spinbutton_mod_mois_naissance_WT, 56, 27);

  spinbutton_mod_mois_recrut_WT_adj = gtk_adjustment_new (1, 1, 12, 1, 10, 10);
  spinbutton_mod_mois_recrut_WT = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton_mod_mois_recrut_WT_adj), 1, 0);
  gtk_widget_show (spinbutton_mod_mois_recrut_WT);
  gtk_fixed_put (GTK_FIXED (fixed11), spinbutton_mod_mois_recrut_WT, 420, 530);
  gtk_widget_set_size_request (spinbutton_mod_mois_recrut_WT, 60, 27);

  spinbutton_mod_annee_naissance_WT_adj = gtk_adjustment_new (1, 1980, 2023, 1, 10, 10);
  spinbutton_mod_annee_naissance_WT = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton_mod_annee_naissance_WT_adj), 1, 0);
  gtk_widget_show (spinbutton_mod_annee_naissance_WT);
  gtk_fixed_put (GTK_FIXED (fixed11), spinbutton_mod_annee_naissance_WT, 540, 460);
  gtk_widget_set_size_request (spinbutton_mod_annee_naissance_WT, 60, 27);

  spinbutton_mod_annee_recrut_WT_adj = gtk_adjustment_new (1, 1990, 2023, 1, 10, 10);
  spinbutton_mod_annee_recrut_WT = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton_mod_annee_recrut_WT_adj), 1, 0);
  gtk_widget_show (spinbutton_mod_annee_recrut_WT);
  gtk_fixed_put (GTK_FIXED (fixed11), spinbutton_mod_annee_recrut_WT, 540, 530);
  gtk_widget_set_size_request (spinbutton_mod_annee_recrut_WT, 60, 27);

  entry_mod_id_WT = gtk_entry_new ();
  gtk_widget_show (entry_mod_id_WT);
  gtk_fixed_put (GTK_FIXED (fixed11), entry_mod_id_WT, 300, 590);
  gtk_widget_set_size_request (entry_mod_id_WT, 300, 50);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_mod_id_WT), 8226);

  entry_mod_mdp_WT = gtk_entry_new ();
  gtk_widget_show (entry_mod_mdp_WT);
  gtk_fixed_put (GTK_FIXED (fixed11), entry_mod_mdp_WT, 300, 660);
  gtk_widget_set_size_request (entry_mod_mdp_WT, 300, 50);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_mod_mdp_WT), 8226);

  label_nom_mod = gtk_label_new (_("Nom :"));
  gtk_widget_show (label_nom_mod);
  gtk_fixed_put (GTK_FIXED (fixed11), label_nom_mod, 50, 30);
  gtk_widget_set_size_request (label_nom_mod, 200, 50);

  label_pre_mod = gtk_label_new (_("Pr\303\251nom :"));
  gtk_widget_show (label_pre_mod);
  gtk_fixed_put (GTK_FIXED (fixed11), label_pre_mod, 50, 100);
  gtk_widget_set_size_request (label_pre_mod, 200, 50);

  label_role_mod = gtk_label_new (_("Role :"));
  gtk_widget_show (label_role_mod);
  gtk_fixed_put (GTK_FIXED (fixed11), label_role_mod, 50, 170);
  gtk_widget_set_size_request (label_role_mod, 200, 50);

  label_cin_role = gtk_label_new (_("CIN :"));
  gtk_widget_show (label_cin_role);
  gtk_fixed_put (GTK_FIXED (fixed11), label_cin_role, 50, 240);
  gtk_widget_set_size_request (label_cin_role, 200, 50);

  label_tele_mod = gtk_label_new (_("T\303\251l\303\251phone  :"));
  gtk_widget_show (label_tele_mod);
  gtk_fixed_put (GTK_FIXED (fixed11), label_tele_mod, 50, 310);
  gtk_widget_set_size_request (label_tele_mod, 200, 50);

  label_sexe_mod = gtk_label_new (_("Sexe :"));
  gtk_widget_show (label_sexe_mod);
  gtk_fixed_put (GTK_FIXED (fixed11), label_sexe_mod, 50, 380);
  gtk_widget_set_size_request (label_sexe_mod, 200, 50);

  label_mdp_mod = gtk_label_new (_("Mot de passe :"));
  gtk_widget_show (label_mdp_mod);
  gtk_fixed_put (GTK_FIXED (fixed11), label_mdp_mod, 50, 660);
  gtk_widget_set_size_request (label_mdp_mod, 200, 50);

  label_id_mod = gtk_label_new (_("Identifiant :"));
  gtk_widget_show (label_id_mod);
  gtk_fixed_put (GTK_FIXED (fixed11), label_id_mod, 50, 590);
  gtk_widget_set_size_request (label_id_mod, 200, 50);

  label_date_naissance_mod = gtk_label_new (_("Date de naissance :"));
  gtk_widget_show (label_date_naissance_mod);
  gtk_fixed_put (GTK_FIXED (fixed11), label_date_naissance_mod, 50, 450);
  gtk_widget_set_size_request (label_date_naissance_mod, 200, 50);

  label_jour_naissance_mod = gtk_label_new (_("jour"));
  gtk_widget_show (label_jour_naissance_mod);
  gtk_fixed_put (GTK_FIXED (fixed11), label_jour_naissance_mod, 240, 450);
  gtk_widget_set_size_request (label_jour_naissance_mod, 70, 50);

  label_mois_naissance_mod = gtk_label_new (_("mois"));
  gtk_widget_show (label_mois_naissance_mod);
  gtk_fixed_put (GTK_FIXED (fixed11), label_mois_naissance_mod, 360, 450);
  gtk_widget_set_size_request (label_mois_naissance_mod, 70, 50);

  label_annee_naissance_mod = gtk_label_new (_("ann\303\251\303\251"));
  gtk_widget_show (label_annee_naissance_mod);
  gtk_fixed_put (GTK_FIXED (fixed11), label_annee_naissance_mod, 480, 450);
  gtk_widget_set_size_request (label_annee_naissance_mod, 70, 50);

  label_date_recrut_mod = gtk_label_new (_("Date de recrutement :"));
  gtk_widget_show (label_date_recrut_mod);
  gtk_fixed_put (GTK_FIXED (fixed11), label_date_recrut_mod, 50, 520);
  gtk_widget_set_size_request (label_date_recrut_mod, 200, 50);

  label_jour_recrut_mod = gtk_label_new (_("jour"));
  gtk_widget_show (label_jour_recrut_mod);
  gtk_fixed_put (GTK_FIXED (fixed11), label_jour_recrut_mod, 240, 520);
  gtk_widget_set_size_request (label_jour_recrut_mod, 70, 50);

  label_mois_recrut_mod = gtk_label_new (_("mois"));
  gtk_widget_show (label_mois_recrut_mod);
  gtk_fixed_put (GTK_FIXED (fixed11), label_mois_recrut_mod, 360, 520);
  gtk_widget_set_size_request (label_mois_recrut_mod, 70, 50);

  label_annee_recrut_mod = gtk_label_new (_("ann\303\251e"));
  gtk_widget_show (label_annee_recrut_mod);
  gtk_fixed_put (GTK_FIXED (fixed11), label_annee_recrut_mod, 480, 520);
  gtk_widget_set_size_request (label_annee_recrut_mod, 70, 50);

  comboboxentry_mod_role_WT = gtk_combo_box_entry_new_text ();
  gtk_widget_show (comboboxentry_mod_role_WT);
  gtk_fixed_put (GTK_FIXED (fixed11), comboboxentry_mod_role_WT, 300, 170);
  gtk_widget_set_size_request (comboboxentry_mod_role_WT, 300, 50);
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry_mod_role_WT), _("Medecin"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry_mod_role_WT), _("Infermier"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry_mod_role_WT), _("Responsable"));

  button_mod_annuler_WT = gtk_button_new ();
  gtk_widget_show (button_mod_annuler_WT);
  gtk_fixed_put (GTK_FIXED (fixed11), button_mod_annuler_WT, 650, 400);
  gtk_widget_set_size_request (button_mod_annuler_WT, 200, 70);

  alignment5 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment5);
  gtk_container_add (GTK_CONTAINER (button_mod_annuler_WT), alignment5);

  hbox4 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox4);
  gtk_container_add (GTK_CONTAINER (alignment5), hbox4);

  image4 = gtk_image_new_from_stock ("gtk-cancel", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image4);
  gtk_box_pack_start (GTK_BOX (hbox4), image4, FALSE, FALSE, 0);

  label89 = gtk_label_new_with_mnemonic (_("   ANNULER"));
  gtk_widget_show (label89);
  gtk_box_pack_start (GTK_BOX (hbox4), label89, FALSE, FALSE, 0);

  button_mod_modif_WT = gtk_button_new ();
  gtk_widget_show (button_mod_modif_WT);
  gtk_fixed_put (GTK_FIXED (fixed11), button_mod_modif_WT, 650, 300);
  gtk_widget_set_size_request (button_mod_modif_WT, 200, 70);

  alignment7 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment7);
  gtk_container_add (GTK_CONTAINER (button_mod_modif_WT), alignment7);

  hbox6 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox6);
  gtk_container_add (GTK_CONTAINER (alignment7), hbox6);

  image6 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image6);
  gtk_box_pack_start (GTK_BOX (hbox6), image6, FALSE, FALSE, 0);

  label95 = gtk_label_new_with_mnemonic (_("   MODIFIER"));
  gtk_widget_show (label95);
  gtk_box_pack_start (GTK_BOX (hbox6), label95, FALSE, FALSE, 0);

  radiobutton_mod_homme_WT = gtk_radio_button_new_with_mnemonic (NULL, _("Homme"));
  gtk_widget_show (radiobutton_mod_homme_WT);
  gtk_fixed_put (GTK_FIXED (fixed11), radiobutton_mod_homme_WT, 300, 380);
  gtk_widget_set_size_request (radiobutton_mod_homme_WT, 150, 50);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton_mod_homme_WT), radiobutton_mod_homme_WT_group);
  radiobutton_mod_homme_WT_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton_mod_homme_WT));

  radiobutton_mod_femme_WT = gtk_radio_button_new_with_mnemonic (NULL, _("Femme"));
  gtk_widget_show (radiobutton_mod_femme_WT);
  gtk_fixed_put (GTK_FIXED (fixed11), radiobutton_mod_femme_WT, 450, 380);
  gtk_widget_set_size_request (radiobutton_mod_femme_WT, 150, 50);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton_mod_femme_WT), radiobutton_mod_homme_WT_group);
  radiobutton_mod_homme_WT_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton_mod_femme_WT));

  label_modifier = gtk_label_new (_("MODIFIER"));
  gtk_widget_show (label_modifier);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 1), label_modifier);
  gtk_widget_set_size_request (label_modifier, 250, 80);

  fixed10 = gtk_fixed_new ();
  gtk_widget_show (fixed10);
  gtk_container_add (GTK_CONTAINER (notebook1), fixed10);

  entry_rechercher_WT = gtk_entry_new ();
  gtk_widget_show (entry_rechercher_WT);
  gtk_fixed_put (GTK_FIXED (fixed10), entry_rechercher_WT, 575, 80);
  gtk_widget_set_size_request (entry_rechercher_WT, 250, 50);
  gtk_entry_set_text (GTK_ENTRY (entry_rechercher_WT), _("recherche"));
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_rechercher_WT), 8226);

  label1 = gtk_label_new (_("Liste des utilisateurs"));
  gtk_widget_show (label1);
  gtk_fixed_put (GTK_FIXED (fixed10), label1, 325, 20);
  gtk_widget_set_size_request (label1, 300, 50);

  comboboxentry_liste_role_WT = gtk_combo_box_entry_new_text ();
  gtk_widget_show (comboboxentry_liste_role_WT);
  gtk_fixed_put (GTK_FIXED (fixed10), comboboxentry_liste_role_WT, 125, 80);
  gtk_widget_set_size_request (comboboxentry_liste_role_WT, 250, 50);
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry_liste_role_WT), _("Medecin"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry_liste_role_WT), _("Infermier"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry_liste_role_WT), _("Responsable"));

  scrolledwindow1 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow1);
  gtk_fixed_put (GTK_FIXED (fixed10), scrolledwindow1, 125, 150);
  gtk_widget_set_size_request (scrolledwindow1, 700, 450);

  treeview_liste_WT = gtk_tree_view_new ();
  gtk_widget_show (treeview_liste_WT);
  gtk_container_add (GTK_CONTAINER (scrolledwindow1), treeview_liste_WT);
  gtk_widget_set_size_request (treeview_liste_WT, 288, 208);

  label_poucentage_homme = gtk_label_new (_("Pourcentage de l'homme :"));
  gtk_widget_show (label_poucentage_homme);
  gtk_fixed_put (GTK_FIXED (fixed10), label_poucentage_homme, 50, 630);
  gtk_widget_set_size_request (label_poucentage_homme, 300, 50);

  label_pourcentage_femme = gtk_label_new (_("Pourcentage de la femme :"));
  gtk_widget_show (label_pourcentage_femme);
  gtk_fixed_put (GTK_FIXED (fixed10), label_pourcentage_femme, 50, 700);
  gtk_widget_set_size_request (label_pourcentage_femme, 300, 50);

  label_homme = gtk_label_new ("");
  gtk_widget_show (label_homme);
  gtk_fixed_put (GTK_FIXED (fixed10), label_homme, 400, 630);
  gtk_widget_set_size_request (label_homme, 200, 50);

  label_femme = gtk_label_new ("");
  gtk_widget_show (label_femme);
  gtk_fixed_put (GTK_FIXED (fixed10), label_femme, 400, 700);
  gtk_widget_set_size_request (label_femme, 200, 50);

  label_afficher = gtk_label_new (_("AFFICHER"));
  gtk_widget_show (label_afficher);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 2), label_afficher);
  gtk_widget_set_size_request (label_afficher, 250, 80);

  fixed9 = gtk_fixed_new ();
  gtk_widget_show (fixed9);
  gtk_container_add (GTK_CONTAINER (notebook1), fixed9);

  entry_sup_id_WT = gtk_entry_new ();
  gtk_widget_show (entry_sup_id_WT);
  gtk_fixed_put (GTK_FIXED (fixed9), entry_sup_id_WT, 216, 240);
  gtk_widget_set_size_request (entry_sup_id_WT, 500, 70);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_sup_id_WT), 8226);

  button_Supprimer_WT = gtk_button_new ();
  gtk_widget_show (button_Supprimer_WT);
  gtk_fixed_put (GTK_FIXED (fixed9), button_Supprimer_WT, 320, 360);
  gtk_widget_set_size_request (button_Supprimer_WT, 300, 70);

  alignment6 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment6);
  gtk_container_add (GTK_CONTAINER (button_Supprimer_WT), alignment6);

  hbox5 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox5);
  gtk_container_add (GTK_CONTAINER (alignment6), hbox5);

  image5 = gtk_image_new_from_stock ("gtk-delete", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image5);
  gtk_box_pack_start (GTK_BOX (hbox5), image5, FALSE, FALSE, 0);

  label94 = gtk_label_new_with_mnemonic (_("   SUPPRIMER"));
  gtk_widget_show (label94);
  gtk_box_pack_start (GTK_BOX (hbox5), label94, FALSE, FALSE, 0);

  label_supprimer = gtk_label_new (_("SUPPRIMER"));
  gtk_widget_show (label_supprimer);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 3), label_supprimer);
  gtk_widget_set_size_request (label_supprimer, 250, 80);

  g_signal_connect ((gpointer) button_aj_annuler_WT, "clicked",
                    G_CALLBACK (on_button_aj_annuler_WT_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_aj_ajouter_WT, "clicked",
                    G_CALLBACK (on_button_aj_ajouter_WT_clicked),
                    NULL);
  g_signal_connect ((gpointer) radiobutton_aj_homme_WT, "toggled",
                    G_CALLBACK (on_radiobutton_aj_homme_WT_toggled),
                    NULL);
  g_signal_connect ((gpointer) radiobutton_aj_femme_WT, "toggled",
                    G_CALLBACK (on_radiobutton_aj_femme_WT_toggled),
                    NULL);
  g_signal_connect ((gpointer) button_mod_annuler_WT, "clicked",
                    G_CALLBACK (on_button_mod_annuler_WT_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_mod_modif_WT, "clicked",
                    G_CALLBACK (on_button_mod_modif_WT_clicked),
                    NULL);
  g_signal_connect ((gpointer) radiobutton_mod_homme_WT, "toggled",
                    G_CALLBACK (on_radiobutton_mod_homme_WT_toggled),
                    NULL);
  g_signal_connect ((gpointer) radiobutton_mod_femme_WT, "toggled",
                    G_CALLBACK (on_radiobutton_mod_femme_WT_toggled),
                    NULL);
  g_signal_connect ((gpointer) treeview_liste_WT, "row_activated",
                    G_CALLBACK (on_treeview_liste_row_WT_activated),
                    NULL);
  g_signal_connect ((gpointer) button_Supprimer_WT, "clicked",
                    G_CALLBACK (on_button_Supprimer_WT_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (administrateur_window, administrateur_window, "administrateur_window");
  GLADE_HOOKUP_OBJECT (administrateur_window, notebook1, "notebook1");
  GLADE_HOOKUP_OBJECT (administrateur_window, fixed12, "fixed12");
  GLADE_HOOKUP_OBJECT (administrateur_window, entry_aj_nom_WT, "entry_aj_nom_WT");
  GLADE_HOOKUP_OBJECT (administrateur_window, entry_aj_prenom_WT, "entry_aj_prenom_WT");
  GLADE_HOOKUP_OBJECT (administrateur_window, entry_aj_cin_WT, "entry_aj_cin_WT");
  GLADE_HOOKUP_OBJECT (administrateur_window, entry_aj_telephone_WT, "entry_aj_telephone_WT");
  GLADE_HOOKUP_OBJECT (administrateur_window, spinbutton_aj_jour_naissance_WT, "spinbutton_aj_jour_naissance_WT");
  GLADE_HOOKUP_OBJECT (administrateur_window, spinbutton_aj_mois_naissance_WT, "spinbutton_aj_mois_naissance_WT");
  GLADE_HOOKUP_OBJECT (administrateur_window, spinbutton_aj_annee_naissance_WT, "spinbutton_aj_annee_naissance_WT");
  GLADE_HOOKUP_OBJECT (administrateur_window, spinbutton_aj_mois_recrut_WT, "spinbutton_aj_mois_recrut_WT");
  GLADE_HOOKUP_OBJECT (administrateur_window, spinbutton_aj_annee_recrut_WT, "spinbutton_aj_annee_recrut_WT");
  GLADE_HOOKUP_OBJECT (administrateur_window, entry_aj_id_WT, "entry_aj_id_WT");
  GLADE_HOOKUP_OBJECT (administrateur_window, entry_aj_mdp_WT, "entry_aj_mdp_WT");
  GLADE_HOOKUP_OBJECT (administrateur_window, spinbutton_aj_jour_recrut_WT, "spinbutton_aj_jour_recrut_WT");
  GLADE_HOOKUP_OBJECT (administrateur_window, label_nom, "label_nom");
  GLADE_HOOKUP_OBJECT (administrateur_window, label_role, "label_role");
  GLADE_HOOKUP_OBJECT (administrateur_window, label_cin, "label_cin");
  GLADE_HOOKUP_OBJECT (administrateur_window, label_tele, "label_tele");
  GLADE_HOOKUP_OBJECT (administrateur_window, label_sexe, "label_sexe");
  GLADE_HOOKUP_OBJECT (administrateur_window, label_date_naissance, "label_date_naissance");
  GLADE_HOOKUP_OBJECT (administrateur_window, label_date_recrut, "label_date_recrut");
  GLADE_HOOKUP_OBJECT (administrateur_window, label_id, "label_id");
  GLADE_HOOKUP_OBJECT (administrateur_window, label_mdp, "label_mdp");
  GLADE_HOOKUP_OBJECT (administrateur_window, label_jour_naissance, "label_jour_naissance");
  GLADE_HOOKUP_OBJECT (administrateur_window, label_mois_naissance, "label_mois_naissance");
  GLADE_HOOKUP_OBJECT (administrateur_window, label_annee_naissance, "label_annee_naissance");
  GLADE_HOOKUP_OBJECT (administrateur_window, label_jour_recrut, "label_jour_recrut");
  GLADE_HOOKUP_OBJECT (administrateur_window, label_mois_recrut, "label_mois_recrut");
  GLADE_HOOKUP_OBJECT (administrateur_window, label_annee_recrut, "label_annee_recrut");
  GLADE_HOOKUP_OBJECT (administrateur_window, label_pre, "label_pre");
  GLADE_HOOKUP_OBJECT (administrateur_window, comboboxentry_aj_role_WT, "comboboxentry_aj_role_WT");
  GLADE_HOOKUP_OBJECT (administrateur_window, button_aj_annuler_WT, "button_aj_annuler_WT");
  GLADE_HOOKUP_OBJECT (administrateur_window, alignment3, "alignment3");
  GLADE_HOOKUP_OBJECT (administrateur_window, hbox2, "hbox2");
  GLADE_HOOKUP_OBJECT (administrateur_window, image2, "image2");
  GLADE_HOOKUP_OBJECT (administrateur_window, label87, "label87");
  GLADE_HOOKUP_OBJECT (administrateur_window, button_aj_ajouter_WT, "button_aj_ajouter_WT");
  GLADE_HOOKUP_OBJECT (administrateur_window, alignment2, "alignment2");
  GLADE_HOOKUP_OBJECT (administrateur_window, hbox1, "hbox1");
  GLADE_HOOKUP_OBJECT (administrateur_window, image1, "image1");
  GLADE_HOOKUP_OBJECT (administrateur_window, label86, "label86");
  GLADE_HOOKUP_OBJECT (administrateur_window, radiobutton_aj_homme_WT, "radiobutton_aj_homme_WT");
  GLADE_HOOKUP_OBJECT (administrateur_window, radiobutton_aj_femme_WT, "radiobutton_aj_femme_WT");
  GLADE_HOOKUP_OBJECT (administrateur_window, label_ajouter, "label_ajouter");
  GLADE_HOOKUP_OBJECT (administrateur_window, fixed11, "fixed11");
  GLADE_HOOKUP_OBJECT (administrateur_window, entry_mod_nom_WT, "entry_mod_nom_WT");
  GLADE_HOOKUP_OBJECT (administrateur_window, entry_mod_prenom_WT, "entry_mod_prenom_WT");
  GLADE_HOOKUP_OBJECT (administrateur_window, entry_mod_cin_WT, "entry_mod_cin_WT");
  GLADE_HOOKUP_OBJECT (administrateur_window, entry_mod_tele_WT, "entry_mod_tele_WT");
  GLADE_HOOKUP_OBJECT (administrateur_window, spinbutton_mod_jour_recrut_WT, "spinbutton_mod_jour_recrut_WT");
  GLADE_HOOKUP_OBJECT (administrateur_window, spinbutton_mod_jour_naissance_WT, "spinbutton_mod_jour_naissance_WT");
  GLADE_HOOKUP_OBJECT (administrateur_window, spinbutton_mod_mois_naissance_WT, "spinbutton_mod_mois_naissance_WT");
  GLADE_HOOKUP_OBJECT (administrateur_window, spinbutton_mod_mois_recrut_WT, "spinbutton_mod_mois_recrut_WT");
  GLADE_HOOKUP_OBJECT (administrateur_window, spinbutton_mod_annee_naissance_WT, "spinbutton_mod_annee_naissance_WT");
  GLADE_HOOKUP_OBJECT (administrateur_window, spinbutton_mod_annee_recrut_WT, "spinbutton_mod_annee_recrut_WT");
  GLADE_HOOKUP_OBJECT (administrateur_window, entry_mod_id_WT, "entry_mod_id_WT");
  GLADE_HOOKUP_OBJECT (administrateur_window, entry_mod_mdp_WT, "entry_mod_mdp_WT");
  GLADE_HOOKUP_OBJECT (administrateur_window, label_nom_mod, "label_nom_mod");
  GLADE_HOOKUP_OBJECT (administrateur_window, label_pre_mod, "label_pre_mod");
  GLADE_HOOKUP_OBJECT (administrateur_window, label_role_mod, "label_role_mod");
  GLADE_HOOKUP_OBJECT (administrateur_window, label_cin_role, "label_cin_role");
  GLADE_HOOKUP_OBJECT (administrateur_window, label_tele_mod, "label_tele_mod");
  GLADE_HOOKUP_OBJECT (administrateur_window, label_sexe_mod, "label_sexe_mod");
  GLADE_HOOKUP_OBJECT (administrateur_window, label_mdp_mod, "label_mdp_mod");
  GLADE_HOOKUP_OBJECT (administrateur_window, label_id_mod, "label_id_mod");
  GLADE_HOOKUP_OBJECT (administrateur_window, label_date_naissance_mod, "label_date_naissance_mod");
  GLADE_HOOKUP_OBJECT (administrateur_window, label_jour_naissance_mod, "label_jour_naissance_mod");
  GLADE_HOOKUP_OBJECT (administrateur_window, label_mois_naissance_mod, "label_mois_naissance_mod");
  GLADE_HOOKUP_OBJECT (administrateur_window, label_annee_naissance_mod, "label_annee_naissance_mod");
  GLADE_HOOKUP_OBJECT (administrateur_window, label_date_recrut_mod, "label_date_recrut_mod");
  GLADE_HOOKUP_OBJECT (administrateur_window, label_jour_recrut_mod, "label_jour_recrut_mod");
  GLADE_HOOKUP_OBJECT (administrateur_window, label_mois_recrut_mod, "label_mois_recrut_mod");
  GLADE_HOOKUP_OBJECT (administrateur_window, label_annee_recrut_mod, "label_annee_recrut_mod");
  GLADE_HOOKUP_OBJECT (administrateur_window, comboboxentry_mod_role_WT, "comboboxentry_mod_role_WT");
  GLADE_HOOKUP_OBJECT (administrateur_window, button_mod_annuler_WT, "button_mod_annuler_WT");
  GLADE_HOOKUP_OBJECT (administrateur_window, alignment5, "alignment5");
  GLADE_HOOKUP_OBJECT (administrateur_window, hbox4, "hbox4");
  GLADE_HOOKUP_OBJECT (administrateur_window, image4, "image4");
  GLADE_HOOKUP_OBJECT (administrateur_window, label89, "label89");
  GLADE_HOOKUP_OBJECT (administrateur_window, button_mod_modif_WT, "button_mod_modif_WT");
  GLADE_HOOKUP_OBJECT (administrateur_window, alignment7, "alignment7");
  GLADE_HOOKUP_OBJECT (administrateur_window, hbox6, "hbox6");
  GLADE_HOOKUP_OBJECT (administrateur_window, image6, "image6");
  GLADE_HOOKUP_OBJECT (administrateur_window, label95, "label95");
  GLADE_HOOKUP_OBJECT (administrateur_window, radiobutton_mod_homme_WT, "radiobutton_mod_homme_WT");
  GLADE_HOOKUP_OBJECT (administrateur_window, radiobutton_mod_femme_WT, "radiobutton_mod_femme_WT");
  GLADE_HOOKUP_OBJECT (administrateur_window, label_modifier, "label_modifier");
  GLADE_HOOKUP_OBJECT (administrateur_window, fixed10, "fixed10");
  GLADE_HOOKUP_OBJECT (administrateur_window, entry_rechercher_WT, "entry_rechercher_WT");
  GLADE_HOOKUP_OBJECT (administrateur_window, label1, "label1");
  GLADE_HOOKUP_OBJECT (administrateur_window, comboboxentry_liste_role_WT, "comboboxentry_liste_role_WT");
  GLADE_HOOKUP_OBJECT (administrateur_window, scrolledwindow1, "scrolledwindow1");
  GLADE_HOOKUP_OBJECT (administrateur_window, treeview_liste_WT, "treeview_liste_WT");
  GLADE_HOOKUP_OBJECT (administrateur_window, label_poucentage_homme, "label_poucentage_homme");
  GLADE_HOOKUP_OBJECT (administrateur_window, label_pourcentage_femme, "label_pourcentage_femme");
  GLADE_HOOKUP_OBJECT (administrateur_window, label_homme, "label_homme");
  GLADE_HOOKUP_OBJECT (administrateur_window, label_femme, "label_femme");
  GLADE_HOOKUP_OBJECT (administrateur_window, label_afficher, "label_afficher");
  GLADE_HOOKUP_OBJECT (administrateur_window, fixed9, "fixed9");
  GLADE_HOOKUP_OBJECT (administrateur_window, entry_sup_id_WT, "entry_sup_id_WT");
  GLADE_HOOKUP_OBJECT (administrateur_window, button_Supprimer_WT, "button_Supprimer_WT");
  GLADE_HOOKUP_OBJECT (administrateur_window, alignment6, "alignment6");
  GLADE_HOOKUP_OBJECT (administrateur_window, hbox5, "hbox5");
  GLADE_HOOKUP_OBJECT (administrateur_window, image5, "image5");
  GLADE_HOOKUP_OBJECT (administrateur_window, label94, "label94");
  GLADE_HOOKUP_OBJECT (administrateur_window, label_supprimer, "label_supprimer");

  return administrateur_window;
}

